name: Deploy Theme (Secure SFTP Pro)

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    name: Secure SFTP Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Checkout local code
      uses: actions/checkout@v4

    - name: 🚀 Copy files to Hostinger via SSH/SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 65002 # El puerto estándar de SSH/SFTP seguro
        source: "./*" # Sube todo el contenido de la carpeta actual
        target: "/home/u663435409/domains/ricardoleal.cloud/public_html/staging/wp-content/themes/generatepress_child/"
        rm: false # No borra la carpeta destino, solo sobrescribe los archivos